### ISSUE TITLE
s3 연동 후 warn로그 

### ISSUE THREAD

**Issue by chanhong-dev** [SLCommunity/511#19]
## 버그에 대한 설명

s3 연동 후 warning로그가 밑의 사진과 같이 출력이 됨니다.
![image](https://user-images.githubusercontent.com/90807343/143575853-277339d9-28cc-4bde-a64c-e3977e30b4c1.png)
![image](https://user-images.githubusercontent.com/90807343/143575869-c1a6d57d-493b-4c14-9bb2-45d520eb58dd.png)
![image](https://user-images.githubusercontent.com/90807343/143575882-4d36cb11-b479-4029-be0c-0a4be5cbe47f.png)

yml파일과 VM option추가로 해결하였습니다. 

## 해결방법

1. application.yml에 로깅 레벨 설정 추가
```
logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error
```

2. Edit Configurations... -> VM options에 `-Dcom.amazonaws.sdk.disableEc2Metadata=true` 추가
![image](https://user-images.githubusercontent.com/90807343/143575557-8d680b25-62b9-4a03-a770-5274a57278f7.png)
